server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health

spring:
  application:
    name: inventory-service

inventory:
  service-url: ${OBSERVER_SERVICE_URL:http://localhost:8033}
  service-name: inventory-service
  transactions:
    - name: CreateOrder
      steps:
        - ReserveStock
        - ReleaseStock