global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: observer-service
    static_configs:
      - targets: ['observer-service:8033']
    metrics_path: /actuator/prometheus

  - job_name: order-service
    static_configs:
      - targets: ['order-service:8082']
    metrics_path: /actuator/prometheus

  - job_name: payment-service
    static_configs:
      - targets: ['payment-service:8083']
    metrics_path: /actuator/prometheus

  - job_name: inventory-service
    static_configs:
      - targets: ['inventory-service:8084']
    metrics_path: /actuator/prometheus

  - job_name: notification-service
    static_configs:
      - targets: ['notification-service:8085']
    metrics_path: /actuator/prometheus
