server:
  port: 8082

spring:
  application:
    name: order-service

# Настройки регистрации шагов в order-service.
order:
  service-url: ${OBSERVER_SERVICE_URL:http://localhost:8033}
  service-name: order-service
  transactions:
    - name: CreateOrder
      steps:
        - StartOrder
        - CallInventory
        - CallPayment
        - CallInventoryRelease
        - CompleteOrderSuccess
        - CompleteOrderByOutOfStock
        - CompleteOrderByPaymentFailed

services:
  inventory-url: http://inventory-service:8084
  payment-url: http://payment-service:8083
  notification-url: http://notification-service:8085