server:
  port: 8083

spring:
  application:
    name: payment-service

# Настройки регистрации шагов в payment-service.
payment:
  service-url: ${OBSERVER_SERVICE_URL:http://localhost:8033}
  service-name: payment-service
  transactions:
    - name: CreateOrder
      steps:
        - ChargePayment
